{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common",
    "version": "2.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7091122"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.3.3.aar",
          "url": "navigation-common-2.3.3.aar",
          "size": 56661,
          "sha512": "325e965ef4c9cabddb525a1a31f3a02447ea9ff6612d77fba44045aad811d90e0d7da56a393559c933faf494f64c2cd8693100f96b83ad5c1e52fa929e7926de",
          "sha256": "40a1dc17aeb0164cd6ec66104f298955d41ea15e2325dadef5c738f4c3bdbdf4",
          "sha1": "46139da75a0adcb2793b9f3d4b37e42c4758d7fb",
          "md5": "3ce09f71a63e59fbc85e5b0e56a0fc5d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.3.3.aar",
          "url": "navigation-common-2.3.3.aar",
          "size": 56661,
          "sha512": "325e965ef4c9cabddb525a1a31f3a02447ea9ff6612d77fba44045aad811d90e0d7da56a393559c933faf494f64c2cd8693100f96b83ad5c1e52fa929e7926de",
          "sha256": "40a1dc17aeb0164cd6ec66104f298955d41ea15e2325dadef5c738f4c3bdbdf4",
          "sha1": "46139da75a0adcb2793b9f3d4b37e42c4758d7fb",
          "md5": "3ce09f71a63e59fbc85e5b0e56a0fc5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-common-2.3.3-sources.jar",
          "url": "navigation-common-2.3.3-sources.jar",
          "size": 35392,
          "sha512": "6144b747e3c9b1fa3284895fc8020b153752e39a25ec361e30f5ba250c502928081cdec95ebede9329da1fb38b08e2791547441806e01f150efa90215cdb8b9c",
          "sha256": "744137f0a89dddb0725af13f84801fb5c53d7ee7c1f6e61478f3fb174146ed18",
          "sha1": "054fdad7d85870fcafa4a103065b329e959dcd43",
          "md5": "03593ce91ecf2c00df561d7d906d1ee4"
        }
      ]
    }
  ]
}
