{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment",
    "version": "2.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7091122"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.3.3.aar",
          "url": "navigation-fragment-2.3.3.aar",
          "size": 19778,
          "sha512": "974e04b1af6e242b0b22bdd674f6e0d39f92bd9fa85b9ed6e3d475d7945cd8b2b91dba4fb5d686882a2b582759ea183a32934a57edba32b10305b572ed5fc312",
          "sha256": "9800c65da0ea1bb834b45597e64a354abbaf30e684d433f39594c88da309ef27",
          "sha1": "de552e94c9967f9b9fb4208aa5ddc6a4594f666a",
          "md5": "511552d0195879222509f83367bbc4c0"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-2.3.3.aar",
          "url": "navigation-fragment-2.3.3.aar",
          "size": 19778,
          "sha512": "974e04b1af6e242b0b22bdd674f6e0d39f92bd9fa85b9ed6e3d475d7945cd8b2b91dba4fb5d686882a2b582759ea183a32934a57edba32b10305b572ed5fc312",
          "sha256": "9800c65da0ea1bb834b45597e64a354abbaf30e684d433f39594c88da309ef27",
          "sha1": "de552e94c9967f9b9fb4208aa5ddc6a4594f666a",
          "md5": "511552d0195879222509f83367bbc4c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-fragment-2.3.3-sources.jar",
          "url": "navigation-fragment-2.3.3-sources.jar",
          "size": 13909,
          "sha512": "75e32815faee288154a64295841bd6d26d6a7023b9bfff1e3d2eed7d2a3311d8806fdea98daa4bd2dd9a736d37598a29269baced1480aaea250270f56ace01cf",
          "sha256": "49ce6624c22d4c67b3275f56d1160615df43c8cd8e2c1b3cd612e0d4f815e279",
          "sha1": "3622ca880ed637740e391a55d7cd5d0869285d29",
          "md5": "bbee3fabe42fcfc1afaf9a2b8baf6a44"
        }
      ]
    }
  ]
}
