{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7091122"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.3.3.aar",
          "url": "navigation-runtime-2.3.3.aar",
          "size": 48053,
          "sha512": "e5e85c37bf488e4e08b9b45d56447cb33ed2dd41cb3d0b9884e05f6d7704138c75e1b12261417fa5ae3b7b06c60bd2c4313202a4340a77b42c39f5cdaa8f94cc",
          "sha256": "e888abd65ecc2211c8b99e8a597a1c358a37a7a7b2bbbf64d1104f3a21a9edd3",
          "sha1": "84968b4f01b7943b1d14f6a13459f72494c0cc17",
          "md5": "5ba10b6b537da68d7c53f97567b8ac5d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.3.3.aar",
          "url": "navigation-runtime-2.3.3.aar",
          "size": 48053,
          "sha512": "e5e85c37bf488e4e08b9b45d56447cb33ed2dd41cb3d0b9884e05f6d7704138c75e1b12261417fa5ae3b7b06c60bd2c4313202a4340a77b42c39f5cdaa8f94cc",
          "sha256": "e888abd65ecc2211c8b99e8a597a1c358a37a7a7b2bbbf64d1104f3a21a9edd3",
          "sha1": "84968b4f01b7943b1d14f6a13459f72494c0cc17",
          "md5": "5ba10b6b537da68d7c53f97567b8ac5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-2.3.3-sources.jar",
          "url": "navigation-runtime-2.3.3-sources.jar",
          "size": 35440,
          "sha512": "4da0d49851cecc1a24be0b5620f5b8ed54152ada59dc886fa768dfd4187ca2affac91dfb3d8e543d945d86b62d20eca29fa0aae314f31813bab3c313d97b08d6",
          "sha256": "4476c37cd7e5ed4f282b6e3c20eaf51a4a3205d4f45e9dc0d0f41e8b67565071",
          "sha1": "9fa9207bda87dd8b232f7303d1b330dd0aff3fed",
          "md5": "b72661f6a41989e4e75b84282f968125"
        }
      ]
    }
  ]
}
