{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui",
    "version": "2.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "7091122"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.3.3.aar",
          "url": "navigation-ui-2.3.3.aar",
          "size": 90091,
          "sha512": "867fe0d44c11eb788a231804ad055fcb69d536c51afe6018b793007b977b85b245779c02b394379f071cf1a0b59885c479d75b3dd29802a985726b7902d73517",
          "sha256": "e1d5b3174273f9000246f5382cace0a9510f8f09df99d47471cedb73fca16d1d",
          "sha1": "a44dfc1aa75377bf2a04d0dd4f1ad52be33929d6",
          "md5": "4015a8972e31176d35255f7b07cf0043"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.3.3.aar",
          "url": "navigation-ui-2.3.3.aar",
          "size": 90091,
          "sha512": "867fe0d44c11eb788a231804ad055fcb69d536c51afe6018b793007b977b85b245779c02b394379f071cf1a0b59885c479d75b3dd29802a985726b7902d73517",
          "sha256": "e1d5b3174273f9000246f5382cace0a9510f8f09df99d47471cedb73fca16d1d",
          "sha1": "a44dfc1aa75377bf2a04d0dd4f1ad52be33929d6",
          "md5": "4015a8972e31176d35255f7b07cf0043"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-2.3.3-sources.jar",
          "url": "navigation-ui-2.3.3-sources.jar",
          "size": 13679,
          "sha512": "ea13b0787ded0e4bd95c52cfd91f9477b0d6ec8a89efd0bdbcb4a5b76211f2f9183fdd0e7f0b00162a867a3b51157c11934514b2243436f15bdc7e895faf8ea7",
          "sha256": "8faa2bed7d4acf1e7a8bbfc30f2cedf81df32caeeb31b16fc2eeaeeadb42e648",
          "sha1": "c3b1c72fb42a6c6ea70970fa444614a2aaa64742",
          "md5": "243d7ce3da37cfbd5c9fb705a4c7ea67"
        }
      ]
    }
  ]
}
